name: capybanse

services:
  postgres:
    image: "postgres:latest"
    container_name: capybanse_postgres
    volumes:
      - ./capybanse_storage/postgres_data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
    restart: always
    networks:
      - capybanse-container-network
    env_file: capybanse.env

  rabbitmq:
    image: "rabbitmq:management"
    container_name: capybanse_rabbitmq
    hostname: capybanse_rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./capybanse_storage/rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - capybanse-container-network

  qdrant:
    image: "qdrant/qdrant"
    container_name: capybanse_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./capybanse_storage/qdrant_storage:/qdrant/storage
      - ./capybanse_storage/qdrant_snapshots:/qdrant/snapshots
      - ./capybanse_storage/qdrant_config.yaml:/qdrant/config/production.yaml
    restart: always
    networks:
      - capybanse-container-network

  clickhouse:
    image: "clickhouse/clickhouse-server"
    container_name: capybanse_clickhouse
    hostname: capybanse_clickhouse
#    ports:
#      - 8123:8123
#      - 8443:8443
    ulimits:
      nproc: 30000
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./capybanse_storage/clickhouse_data:/var/lib/clickhouse
    restart: always
    networks:
      - capybanse-container-network


  capybanse_event_parser:
    image: "ideeockus/capybanse_event_parser:latest"

    container_name: event_parser
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - capybanse-container-network
    env_file: capybanse.env
#
  capybanse_event_handler:
    image: "ideeockus/capybanse_event_handler:latest"
#    image: "capybanse_event_handler:latest"

    container_name: event_handler
    volumes:
      - ./capybanse_storage/model_data:/var/capybanse/model
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - qdrant
    networks:
      - capybanse-container-network
    env_file: capybanse.env

  capybanse_rec_service:
    image: "ideeockus/capybanse_rec_service:latest"
#    image: "capybanse_rec_service:latest"

    container_name: rec_service
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - qdrant
    networks:
      - capybanse-container-network
    env_file: capybanse.env

  capybanse_tg_bot:
    image: "ideeockus/capybanse_resonanse_bot:latest"
    container_name: tg_bot
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - capybanse-container-network
    env_file: capybanse.env

networks:
  capybanse-container-network:


