name: capybanse

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
#    expose:
#      - 5432:5432
    restart: always
#    deploy:
#      resources:
#        limits:
#          memory: 2G
    networks:
      - capybanse-container-network
    env_file: capybanse.env

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    hostname: rabbitmq
#    expose:
#      - "5672:5672"
#    ports:
#      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - capybanse-container-network

  qdrant:
    image: "qdrant/qdrant"
    container_name: qdrant
#    ports:
#      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
      - ./qdrant_snapshots:/qdrant/snapshots
      - ./qdrant_config.yaml:/qdrant/config/production.yaml
    restart: always
    networks:
      - capybanse-container-network

  clickhouse:
    image: "clickhouse/clickhouse-server"
    container_name: clickhouse
    hostname: clickhouse
    ulimits:
      nproc: 30000
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    restart: always
    networks:
      - capybanse-container-network


  capybanse_event_parser:
    image: "ideeockus/capybanse/event_parser:latest"
    container_name: event_parser
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - capybanse-container-network

  capybanse_event_handler:
    image: "ideeockus/capybanse/event_handler:latest"
    container_name: event_handler
    volumes:
      - ./model_data:/var/capybanse/model
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - qdrant
    networks:
      - capybanse-container-network

  capybanse_rec_service:
    image: "ideeockus/capybanse/rec_service:latest"
    container_name: rec_service
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - qdrant
    networks:
      - capybanse-container-network

  capybanse_tg_bot:
    image: "ideeockus/capybanse/resonanse_bot:latest"
    container_name: tg_bot
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - capybanse-container-network

networks:
  capybanse-container-network:


