[tool.poetry]
name = "parsers"
version = "2024.0.1"
description = "event sources parsing"
authors = ["Radmir <radmirka745@gmail.com>"]
license = "AGPL-3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
