name: Build and Push Docker images

on:
  push:
    branches:
      - master
    paths:
      - 'capybanse_common/**'
      - 'event_handler/**'
      - 'parsers/**'
      - 'recommendation_service/**'
      - '.github/workflows/on_common_change.yml'

jobs:
  build_common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build capybanse_common
        uses: docker/build-push-action@v4
        with:
          context: ./capybanse_common
          file: ./capybanse_common/Dockerfile
          push: true
          load: true
          tags: ideeockus/capybanse_common
          outputs: type=docker,dest=/tmp/capybanse_common.tar

      - name: Upload capybanse_common artifaact
        uses: actions/upload-artifact@v4
        with:
          name: capybanse_common
          path: /tmp/capybanse_common.tar

  build_services:
    needs: build_common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./event_handler
            image: ideeockus/capybanse_event_handler
          - context: ./parsers
            image: ideeockus/capybanse_event_parser
          - context: ./recommendation_service
            image: ideeockus/capybanse_rec_service

    steps:
      - name: Download capybanse_common artifact
        uses: actions/download-artifact@v4
        with:
          name: capybanse_common
          path: /tmp

      - name: Load image capybanse_common
        run: |
          docker load --input /tmp/capybanse_common.tar
          docker image ls -a

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: ${{ matrix.image }}:latest

      - name: Clean up
        run: docker rmi ${{ matrix.image }}:latest
