name: Build and Push Docker images

on:
  push:
    branches:
      - main
    paths:
      - 'capybanse_common/**'
      - 'event_handler/**'
      - 'parsers/**'
      - 'recommendation_service/**'
      - '.github/workflows/docker-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./capybanse_common
            image: ideeockus/capybanse_common
          - context: ./event_handler
            image: ideeockus/capybanse_event_handler
          - context: ./parsers
            image: ideeockus/capybanse_event_parser
          - context: ./recommendation_service
            image: ideeockus/capybanse_rec_service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: ${{ matrix.image }}:latest

      - name: Clean up
        run: docker rmi ${{ matrix.image }}:latest
